export const COMMUNE_NAMES_AR = {
    // Wilaya 16 - Algiers
    "Alger Centre": "الجزائر الوسطى",
    "Sidi M'hamed": "سيدي امحمد",
    "El Madania": "المدنية",
    "Belouizdad": "بلوزداد",
    "Bab El Oued": "باب الوادي",
    "Bologhine": "بولوغين",
    "Casbah": "القصبة",
    "Oued Koriche": "وادي قريش",
    "Bir Mourad Rais": "بئر مراد رايس",
    "El Biar": "البيار",
    "Bouzareah": "بوزريعة",
    "Ben Aknoun": "بن عكنون",
    "Hydra": "حيدة",
    "El Harrach": "الحراش",
    "Bourouba": "بوروبة",
    "Hussein Dey": "حسين داي",
    "Kouba": "القبة",
    "Bachedjerah": "باش جراح",
    "Dar El Beida": "الدار البيضاء",
    "Bab Ezzouar": "باب الزوار",
    "Ben Aknoun": "بن عكنون",
    "Dely Ibrahim": "دالي ابراهيم",
    "El Hammamet": "الحمامات",
    "Rais Hamidou": "الرايس حميدو",
    "Djasr Kasentina": "جسر قسنطينة",
    "El Mouradia": "المرادية",
    "Hydra": "حيدرة",
    "Mohammadia": "المحمدية",
    "Bordj El Kiffan": "برج الكيفان",
    "El Magharia": "المقارية",
    "Beni Messous": "بني مسوس",
    "Les Eucalyptus": "الكاليتوس",
    "Birtouta": "بئر توتة",
    "Tessala El Merdja": "تسالة المرجة",
    "Ouled Chebel": "اولاد شبل",
    "Sidi Moussa": "سيدي موسى",
    "Ain Taya": "عين طاية",
    "Bordj El Bahri": "برج البحري",
    "El Marsa": "المرسى",
    "Herraoua": "هراوة",
    "Rouiba": "رويبة",
    "Reghaia": "رغاية",
    "Ain Benian": "عين بنيان",
    "Staoueli": "سطاوالي",
    "Zeralda": "زرالدة",
    "Maalma": "المعالمة",
    "Rahmania": "الرحمانية",
    "Souidania": "سويدانية",
    "Cheraga": "الشراقة",
    "Ouled Fayet": "اولاد فايت",
    "El Achour": "العاشور",
    "Draria": "درارية",
    "Douira": "دويرة",
    "Baba Hassen": "بابا احسن",
    "Khraissia": "خرايسية",
    "Saoula": "السحاولة",

    // Add more as needed or automate this list
};
